# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4838a5ff57a3723424040c397dcc1c536f84507991fa44339bf3031056a26c6233886b770a9281a51fd39256955c24593cb649f64d7747d38ea37616c8f281e0

test:
  secret_key_base: 878e2cb6efe3c41eafaf170f68301598f136abe5bcce1a71b54c70356770e923dadb8c5c828d280b3fc7800bff321f6aa25fc0f412735a1e551d2f1796886946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
